### ISSUE TITLE
Story: Price list - bulk edit table

### ISSUE THREAD

**Issue by fPolic** [medusajs/admin#443]
**Story**
- add a bulk edit table component for managing variant item prices

**Tasks**
- [x] https://github.com/medusajs/admin/issues/506
- [x] https://github.com/medusajs/admin/issues/508
- [ ] https://github.com/medusajs/admin/issues/509

**Resources**
 - [Figma](https://www.figma.com/file/a5Mb7n6lelmmFU28wqQybY/Customer-Groups%2C-Promotions-%26-Pricing?node-id=459%3A11029)
